# Kitty config — minimal, font Noctalia
# Warna akan disinkronkan dari palet Noctalia (app theming)

font_family      JetBrainsMono Nerd Font
font_size        11.0

# Padding nyaman
window_padding_width 8

# Opsi umum
hide_window_decorations yes
mouse_hide_wait 2.0
placement_strategy center

# Tema dari Noctalia (palet turun dari wallpaper)
include themes/noctalia.conf

# Transparan: background kitty mati, tembus ke wallpaper
background_opacity 0.0

# Aksen aktif = merah coral #FD4663 (setelah include theme biar menang)
active_border_color #fd4663
url_color           #fd4663
color1              #fd4663
color9              #fd4663
